### PR TITLE
null safety-support

### PR DESCRIPTION
**Pull request by vishna**
Not exactly sure if what I did here is correct but tests pass ¯\_(ツ)_/¯ so feel free to reuse/redact this code if it's any good.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Looking good, thanks!

**Comment by mehmetf** [comment]
Thanks for this!

Looking over the code though, I have slight concerns. For instance, _injectedChild seems to be nullable but throughout the code, it is being used directly without checking whether it is null. The setter pattern is tricky to handle: https://dart.dev/null-safety/faq#how-do-i-deal-with-attributes-that-have-setters and in this case we cannot mark it `late` either since it is being saved to `previous` which can be nullable.

We likely need @rrousselGit 's advice here.

- Are _injectedChild, _wrappedChild _getters_ ever supposed to return null?
- Do we expect null in child parameter for things like:

```
const SingleChildStatelessWidget({Key? key, Widget? child})
```

or is child `required` here?

**Comment by mehmetf** [comment]
Related to required child. It does seem `Nested` does not require its `child` parameter, however that makes reasoning about this line complicated:

```
var nextNode = _parent?.injectedChild ?? widget._child;
```

It appears, nextNode is supposed to be non-null here so we either expect a `_parent` or a `widget._child` to be present. Is that accurate?

**Comment by rrousselGit** [comment]
> Do we expect null in child parameter for things like:

The child is optional. That is the entire point of the package, to not use _child_ and make a list of widgets rather than a tree. 

> It appears, nextNode is supposed to be non-null here so we either expect a _parent or a widget._child to be present. Is that accurate? 

Yes.
This is because the _children_ parameter of _Nested_ is required to not be empty. 

So that node is either the first _children_ item, or Nested's _child_

**Pull request merged**
